services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hello-world
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "wal_level=logical"]

volumes:
  postgres_data: